### ISSUE TITLE
custom dataset / simple product recsys

### ISSUE THREAD

**Issue by lucmichalski** [BeelGroup/Auto-Surprise#39]
Hi @thededlier , all,

Hope you are all well !

I was wondering if you could explain quickly how to use a simple csv file with columns like productId, customerId and ratings with auto surprise ?

Also, would it be complicated to create a Fastapi server ?

Thanks for any insights or inputs on these questions.

Cheers,
Luc Michalski

**Comment by thededlier** [comment]
Hi @lucmichalski 

Since `Auto-Surprise` is based on `Surprise`, you can load a custom dataset using one of the methods provided by it. You can follow the links [here](https://auto-surprise.readthedocs.io/en/stable/usage/manual.html#loading-the-dataset).

I haven't used Fastapi myself, but I don't see any reason why it wouldn't be possible to have an API call for training (of course this would need to be setup as an asynchronous job) and producing recommendations from a model.

Let me know if that helps
